from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def generate_report(image_name, prediction, confidence):

    os.makedirs("reports", exist_ok=True)
    # Convert internal class names to user-friendly labels
    if prediction == "ok_front":
       display_prediction = "GOOD PRODUCT"
    elif prediction == "def_front":
       display_prediction = "DEFECTIVE PRODUCT"
    else:
        display_prediction = prediction

    filename = f"reports/Inspection_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>VisionQC-AI Inspection Report</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Image:</b> {image_name}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Prediction:</b> {display_prediction}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Confidence:</b> {confidence}%", styles["BodyText"]))

    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y')}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Time:</b> {datetime.now().strftime('%I:%M:%S %p')}", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Model Information</b>", styles["Heading2"]))

    story.append(Paragraph("Model : MobileNetV2", styles["BodyText"]))

    story.append(Paragraph("Framework : TensorFlow", styles["BodyText"]))

    story.append(Paragraph("Backend : Flask", styles["BodyText"]))

    story.append(Paragraph("Input Resolution : 224 x 224", styles["BodyText"]))

    story.append(Paragraph("Validation Accuracy : 98.6%", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(
        "This report was automatically generated by VisionQC-AI.",
        styles["Italic"]
    ))

    doc.build(story)

    return filename